import { IncidentPriority } from "@/app/utils/IncidentPriority";
import { IncidentStatus } from "@/app/utils/IncidentStatus";
import { IncidentDetail } from "@/app/models/IncidentDetail";

export const initialIncidents: IncidentDetail[] = [
  {
    id: BigInt(123),  // Attention à utiliser BigInt pour id
    titre: "Erreur de connexion à la base SG_ABS_PROD",
    description: "L'incident concerne une erreur persistante de connexion à la base de données SG_ABS_PROD, empêchant l'accès aux données essentielles pour les opérations en production. Ce problème a été signalé suite à la maintenance planifiée et impacte la continuité du service.",
    statutIncident: IncidentStatus.AFFECTE,
    gravite: "Haute",
    priorite: IncidentPriority.ELEVEE,
    dateAttribution: "2025-05-10T09:30:00",
    dateResolution: "", // pas encore résolu
    dateDeclaration: "2025-05-10",
    clientSub: "SUB123",
    client_fullName: "Ahmed Benali",
    client_igg: "IGG123",
    coeDevSub: "DEV456",
    environnement: "Prod",
    application: "Database",
    coeDev_firstName: "Mahmoud",
    client_serviceName: "Database",
    coeDev_serviceName: "Support IT",
    client_firstName: "Ahmed",
    client_role: "Client",
    client_lastName: "Benali",
    client_mail: "ahmed.benali@example.com",
    coeDev_lastName: "Fassi",
    coeDev_igg: "DEVIGG456",
    coeDev_role: "Analyste",
    coeDev_fullName: "Mahmoud Fassi",
    coeDev_mail: "mahfassi@example.com"
  },
  {
    id: BigInt(716),
    titre: "Timeout lors de l'ouverture d'un compte client",
    description: "Des timeouts récurrents sont observés lors de la tentative d'ouverture de comptes clients via le portail. Cette défaillance ralentit fortement l'expérience utilisateur et peut entraîner une perte de clients potentiels, nécessitant une investigation urgente.",
    statutIncident: IncidentStatus.RESOLU,
    gravite: "Moyenne",
    priorite: IncidentPriority.MOYENNE,
    dateAttribution: "2025-05-12T09:00:00",
    dateResolution: "",
    dateDeclaration: "2025-05-12",
    clientSub: "SUB124",
    client_fullName: "Sara El Amrani",
    client_igg: "IGG124",
    coeDevSub: "DEV457",
    environnement: "Prod",
    application: "Client Portal",
    coeDev_firstName: "Mehdi",
    client_serviceName: "Client Portal",
    coeDev_serviceName: "Support Client",
    client_firstName: "Sara",
    client_role: "Client",
    client_lastName: "El Amrani",
    client_mail: "sara.elamrani@example.com",
    coeDev_lastName: "Bouhlaoui",
    coeDev_igg: "DEVIGG457",
    coeDev_role: "Développeur",
    coeDev_fullName: "Mehdi Bouhlaoui",
    coeDev_mail: "mehdi.bouhlaoui@example.com"
  },
  {
    id: BigInt(182),
    titre: "Problème de lenteur sur interface de virements",
    description: "L'interface de virements présente des temps de réponse très longs, perturbant les opérations bancaires. Une surcharge réseau est suspectée, et une analyse approfondie est en cours pour identifier la cause et remédier au problème.",
    statutIncident: IncidentStatus.PRIS_EN_CHARGE,
    gravite: "Moyenne",
    priorite: IncidentPriority.MOYENNE,
    dateAttribution: "2025-05-08T10:00:00",
    dateResolution: "",
    dateDeclaration: "2025-05-08",
    clientSub: "SUB125",
    client_fullName: "Khalid Mounir",
    client_igg: "IGG125",
    coeDevSub: "DEV458",
    environnement: "Dev",
    application: "Payments",
    coeDev_firstName: "Fatima Ezzahra",
    client_serviceName: "Payments",
    coeDev_serviceName: "Réseau",
    client_firstName: "Khalid",
    client_role: "Client",
    client_lastName: "Mounir",
    client_mail: "khalid.mounir@example.com",
    coeDev_lastName: "Arbaoui",
    coeDev_igg: "DEVIGG458",
    coeDev_role: "Analyste Réseau",
    coeDev_fullName: "Fatima Ezzahra Arbaoui",
    coeDev_mail: "fatima.arbaoui@example.com"
  },
  // Continue ainsi pour les autres incidents...
];
